//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix.CabUpgrade.Utils.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helix.CabUpgrade.Utils.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667769580,
        ///   &quot;name&quot; : &quot;Amp Dua Cab A&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;block0&quot; : {
        ///     &quot;@bypassvolume&quot; : 1.0,
        ///     &quot;@enabled&quot; : true,
        ///     &quot;@model&quot; : &quot;HD2_AmpMoonJump&quot;,
        ///     &quot;@no_snapshot_bypass&quot; : false,
        ///     &quot;@path&quot; : 0,
        ///     &quot;@position&quot; : 0,
        ///     &quot;@type&quot; : 1,
        ///     &quot;Bass&quot; : 0.40,
        ///     &quot;Bias&quot; :  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amp_Dual_Cab_A {
            get {
                return ResourceManager.GetString("Amp Dual Cab A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667769580,
        ///   &quot;name&quot; : &quot;Amp Sng Cab A&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;block0&quot; : {
        ///     &quot;@bypassvolume&quot; : 1.0,
        ///     &quot;@enabled&quot; : true,
        ///     &quot;@model&quot; : &quot;HD2_AmpMoonJump&quot;,
        ///     &quot;@no_snapshot_bypass&quot; : false,
        ///     &quot;@path&quot; : 0,
        ///     &quot;@position&quot; : 2,
        ///     &quot;@type&quot; : 1,
        ///     &quot;Bass&quot; : 0.40,
        ///     &quot;Bias&quot; :  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amp_Single_Cab_A {
            get {
                return ResourceManager.GetString("Amp Single Cab A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667769579,
        ///   &quot;name&quot; : &quot;Joined AC path A&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;block0&quot; : {
        ///     &quot;@bypassvolume&quot; : 1.0,
        ///     &quot;@cab&quot; : &quot;cab0&quot;,
        ///     &quot;@enabled&quot; : true,
        ///     &quot;@model&quot; : &quot;HD2_AmpMoonJump&quot;,
        ///     &quot;@no_snapshot_bypass&quot; : false,
        ///     &quot;@path&quot; : 0,
        ///     &quot;@position&quot; : 3,
        ///     &quot;@type&quot; : 3,
        ///     &quot;Bas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Joined_AC_path_A {
            get {
                return ResourceManager.GetString("Joined AC path A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667769579,
        ///   &quot;name&quot; : &quot;Joined AC path B&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;inputA&quot; : {
        ///     &quot;@input&quot; : 1,
        ///     &quot;@model&quot; : &quot;HD2_AppDSPFlow1Input&quot;,
        ///     &quot;decay&quot; : 0.50,
        ///     &quot;noiseGate&quot; : false,
        ///     &quot;threshold&quot; : -48.0
        ///    },
        ///    &quot;inputB&quot; : {
        ///     &quot;@input&quot; : 0,
        ///     &quot;@model&quot; : &quot;HD2_AppDSPFlow2Input&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Joined_AC_path_B {
            get {
                return ResourceManager.GetString("Joined AC path B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55574528,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1668108367,
        ///   &quot;name&quot; : &quot;Legacy A&amp;C&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;block0&quot; : {
        ///     &quot;@bypassvolume&quot; : 1.0,
        ///     &quot;@cab&quot; : &quot;cab0&quot;,
        ///     &quot;@enabled&quot; : true,
        ///     &quot;@model&quot; : &quot;HD2_AmpJazzRivet120&quot;,
        ///     &quot;@no_snapshot_bypass&quot; : false,
        ///     &quot;@path&quot; : 0,
        ///     &quot;@position&quot; : 2,
        ///     &quot;@type&quot; : 3,
        ///     &quot;Bass&quot; : 0.560,
        ///     &quot;Bright [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legacy_Amp_and_Cab {
            get {
                return ResourceManager.GetString("Legacy Amp and Cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55574528,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1668095700,
        ///   &quot;name&quot; : &quot;Legacy Dual Cab&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;block0&quot; : {
        ///     &quot;@cab&quot; : &quot;cab0&quot;,
        ///     &quot;@enabled&quot; : true,
        ///     &quot;@mic&quot; : 5,
        ///     &quot;@model&quot; : &quot;HD2_Cab2x12MailC12Q&quot;,
        ///     &quot;@no_snapshot_bypass&quot; : false,
        ///     &quot;@path&quot; : 0,
        ///     &quot;@position&quot; : 2,
        ///     &quot;@type&quot; : 4,
        ///     &quot;Distance&quot; : 2.50,
        ///     &quot;EarlyRefl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legacy_Dual_Cab {
            get {
                return ResourceManager.GetString("Legacy Dual Cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667773712,
        ///   &quot;name&quot; : &quot;Legacy Sngl Cab&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;block0&quot; : {
        ///     &quot;@enabled&quot; : true,
        ///     &quot;@mic&quot; : 1,
        ///     &quot;@model&quot; : &quot;HD2_Cab4x12XXLV30&quot;,
        ///     &quot;@no_snapshot_bypass&quot; : false,
        ///     &quot;@path&quot; : 0,
        ///     &quot;@position&quot; : 2,
        ///     &quot;@type&quot; : 2,
        ///     &quot;Distance&quot; : 2.0,
        ///     &quot;EarlyReflect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legacy_Single_Cab {
            get {
                return ResourceManager.GetString("Legacy Single Cab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667773712,
        ///   &quot;name&quot; : &quot;Legacy Sngl Cab&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;dsp0&quot; : {
        ///    &quot;inputA&quot; : {
        ///     &quot;@input&quot; : 1,
        ///     &quot;@model&quot; : &quot;HD2_AppDSPFlow1Input&quot;,
        ///     &quot;decay&quot; : 0.10,
        ///     &quot;noiseGate&quot; : false,
        ///     &quot;threshold&quot; : -48.0
        ///    },
        ///    &quot;inputB&quot; : {
        ///     &quot;@input&quot; : 0,
        ///     &quot;@model&quot; : &quot;HD2_AppDSPFlow2Input&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Legacy_Single_Cab_Path_B {
            get {
                return ResourceManager.GetString("Legacy Single Cab Path B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;HD2_Cab1x10PrincessCopperhead&quot;: {
        ///	  &quot;Name&quot;: &quot;1x10 US Princess&quot;,
        ///	  &quot;Id&quot;: &quot;HD2_CabMicIr_1x10USPrincess&quot;,
        ///	  &quot;DefaultMic&quot;: 11
        ///	},
        ///	&quot;HD2_Cab1x12Grammatico5E3&quot;: {
        ///	  &quot;Name&quot;: &quot;1x12 Grammatico&quot;,
        ///	  &quot;Id&quot;: &quot;HD2_CabMicIr_1x12Grammatico&quot;,
        ///	  &quot;DefaultMic&quot;: 11
        ///	},
        ///	&quot;HD2_Cab1x12USDeluxe&quot;: {
        ///	  &quot;Name&quot;: &quot;1x12 US Deluxe&quot;,
        ///	  &quot;Id&quot;: &quot;HD2_CabMicIr_1x12USDeluxe&quot;,
        ///	  &quot;DefaultMic&quot;: 0
        ///	},
        ///	&quot;HD2_Cab1x12CaliExt&quot;: {
        ///	  &quot;Name&quot;: &quot;1x12 Cali Ext&quot;,
        ///	  &quot;Id&quot;: &quot;HD2_CabMicIr_1x12CaliEXT&quot;,
        ///	  &quot;DefaultMic&quot;: 0
        ///	},
        ///	&quot;HD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667769580,
        ///   &quot;name&quot; : &quot;Sng Cab 3SS 2P&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;controller&quot; : {
        ///    &quot;dsp0&quot; : {
        ///     &quot;block1&quot; : {
        ///      &quot;Distance&quot; : {
        ///       &quot;@controller&quot; : 19,
        ///       &quot;@max&quot; : 12.0,
        ///       &quot;@min&quot; : 1.0,
        ///       &quot;@snapshot_disable&quot; : false
        ///      },
        ///      &quot;Mic&quot; : {
        ///       &quot;@controller&quot; : 19,
        ///       &quot;@max&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sng_Cab_3SS_2P {
            get {
                return ResourceManager.GetString("Sng Cab 3SS 2P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;data&quot; : {
        ///  &quot;device&quot; : 2162689,
        ///  &quot;device_version&quot; : 55574528,
        ///  &quot;meta&quot; : {
        ///   &quot;application&quot; : &quot;HX Edit&quot;,
        ///   &quot;appversion&quot; : 55083877,
        ///   &quot;build_sha&quot; : &quot;ec7605f&quot;,
        ///   &quot;modifieddate&quot; : 1667769580,
        ///   &quot;name&quot; : &quot;Sng Cab A 2SS 1P&quot;
        ///  },
        ///  &quot;tone&quot; : {
        ///   &quot;controller&quot; : {
        ///    &quot;dsp0&quot; : {
        ///     &quot;block1&quot; : {
        ///      &quot;Mic&quot; : {
        ///       &quot;@controller&quot; : 19,
        ///       &quot;@max&quot; : 11,
        ///       &quot;@min&quot; : 0,
        ///       &quot;@snapshot_disable&quot; : false
        ///      }
        ///     }
        ///    }
        ///   },
        ///   &quot;dsp0&quot; : {
        ///    &quot;block0&quot; : {
        ///     &quot;@bypa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sng_Cab_A_2SS_1P {
            get {
                return ResourceManager.GetString("Sng Cab A 2SS 1P", resourceCulture);
            }
        }
    }
}
